### ISSUE TITLE
Filling a bottle crashes game

### ISSUE THREAD

**Issue by superdumpling** [Tfarcenim/DankStorageFabric#29]
dankstorage-2.1-1.17.1
2 danks in inventory, both set to filtered pickup and bag mode

filling a glass bottle with water from a water block causes crash, also occasionally crashes when filling a bucket with lava & water

-- log
Description: Unexpected error

java.lang.RuntimeException: Attempted to get inventory on client
	at tfar.dankstorage.utils.Utils.getInventory(Utils.java:221)
	at tfar.dankstorage.event.MixinHooks.onItemPickup(MixinHooks.java:43)
	at tfar.dankstorage.event.MixinHooks.interceptItem(MixinHooks.java:32)
	at net.minecraft.class_1661.handler$bde000$interceptItems(class_1661.java:2187)
	at net.minecraft.class_1661.method_7394(class_1661.java)
	at net.minecraft.class_5328.method_30270(class_5328.java:44)
	at net.minecraft.class_5328.method_30012(class_5328.java:56)
	at net.minecraft.class_1754.method_7725(class_1754.java:66)
	at net.minecraft.class_1754.method_7836(class_1754.java:57)
	at net.minecraft.class_1799.method_7913(class_1799.java:254)
	at net.minecraft.class_636.method_2919(class_636.java:361)
	at net.optifine.override.PlayerControllerOF.method_2919(PlayerControllerOF.java:80)
	at net.minecraft.class_310.method_1583(class_310.java:1666)
	at net.minecraft.class_310.redirect$zep000$onDoItemUse(class_310.java:5109)
	at net.minecraft.class_310.method_1508(class_310.java:1900)
	at net.minecraft.class_310.method_1574(class_310.java:1728)
	at net.minecraft.class_310.method_1523(class_310.java:1081)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at tfar.dankstorage.utils.Utils.getInventory(Utils.java:221)
	at tfar.dankstorage.event.MixinHooks.onItemPickup(MixinHooks.java:43)
	at tfar.dankstorage.event.MixinHooks.interceptItem(MixinHooks.java:32)
	at net.minecraft.class_1661.handler$bde000$interceptItems(class_1661.java:2187)
	at net.minecraft.class_1661.method_7394(class_1661.java)
	at net.minecraft.class_5328.method_30270(class_5328.java:44)
	at net.minecraft.class_5328.method_30012(class_5328.java:56)
	at net.minecraft.class_1754.method_7725(class_1754.java:66)
	at net.minecraft.class_1754.method_7836(class_1754.java:57)
	at net.minecraft.class_1799.method_7913(class_1799.java:254)
	at net.minecraft.class_636.method_2919(class_636.java:361)
	at net.optifine.override.PlayerControllerOF.method_2919(PlayerControllerOF.java:80)
	at net.minecraft.class_310.method_1583(class_310.java:1666)
	at net.minecraft.class_310.redirect$zep000$onDoItemUse(class_310.java:5109)
	at net.minecraft.class_310.method_1508(class_310.java:1900)

**Comment by Naofal-Helal** [comment]
I get the same crash log when crafting sugar from honey bottles
```
java.lang.RuntimeException: Attempted to get inventory on client
at tfar.dankstorage.utils.Utils.getInventory(Utils.java:221)
...
```

**Comment by Tfarcenim** [comment]
Should no longer happen, a mod was attempting to craft items on the client

**Comment by Monster-Zer0** [comment]
I got a report of this crash recently happening https://github.com/TeamAOF/All-of-Fabric-4/issues/125
