### ISSUE TITLE
Right clicking an entity with a dank in construction mode crashes to desktop.

### ISSUE THREAD

**Issue by SuddenTurmoil** [Tfarcenim/DankStorageFabric#34]
Right clicking any entity with a dank while it is in construction mode causes the client to crash to desktop.
AoF4 Pre9, v 2.2.1 of dank storage.
Logs here: https://paste.ee/p/5PwwC

**Comment by tariqk** [comment]
Problem still persists — when trying to right-click a mob entity, will crash straight to desktop.

AOF4 1.0.1, Dank Storage 2.2.1-1.17.1

Crash Log: 

```
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 10/30/21, 4:43 PM
Description: Unexpected error

java.lang.RuntimeException: Attempted to get inventory on client
	at tfar.dankstorage.utils.Utils.getInventory(Utils.java:234)
	at tfar.dankstorage.item.DankItem.method_7847(DankItem.java:166)
	at net.minecraft.class_1799.method_7920(class_1799.java:398)
	at net.minecraft.class_1657.method_7287(class_1657.java:1072)
	at net.minecraft.class_636.method_2905(class_636.java:394)
	at net.minecraft.class_310.method_1583(class_310.java:1631)
	at net.minecraft.class_310.method_1508(class_310.java:1900)
	at net.minecraft.class_310.method_1574(class_310.java:1728)
	at net.minecraft.class_310.method_1523(class_310.java:1081)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at tfar.dankstorage.utils.Utils.getInventory(Utils.java:234)
	at tfar.dankstorage.item.DankItem.method_7847(DankItem.java:166)
	at net.minecraft.class_1799.method_7920(class_1799.java:398)
	at net.minecraft.class_1657.method_7287(class_1657.java:1072)
	at net.minecraft.class_636.method_2905(class_636.java:394)
	at net.minecraft.class_310.method_1583(class_310.java:1631)
	at net.minecraft.class_310.method_1508(class_310.java:1900)

-- Affected level --
Details:
	All players: 1 total; [class_746['tariqk'/85, l='ClientLevel', x=-482.82, y=70.00, z=-650.28]]
	Chunk stats: 1024, 256
	Level dimension: minecraft:overworld
	Level spawn location: World: (-64,64,-144), Section: (at 0,0,0 in -4,4,-9; chunk contains blocks -64,0,-144 to -49,255,-129), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 1186387 game time, 1640963 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Generated Resources, Fabric Mods, charmonium/journeyman, KubeJS Resource Pack [assets], Bare+Bones+1.17.zip

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (amd64) version 5.13.0-7614-generic
	Java Version: 16.0.1, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
	Memory: 2898982912 bytes (2764 MiB) / 6442450944 bytes (6144 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-9100 CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 11
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: CoffeeLake-S GT2 [UHD Graphics 630]
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0x3e91
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 8020.14
	Virtual memory used (MB): 10185.25
	Swap memory total (MB): 4095.49
	Swap memory used (MB): 2575.45
	JVM Flags: 2 total; -Xms6144m -Xmx6144m
	Fabric Mods: 
		addendum: Addendum 1.0.2
		additionaladditions: Additional Additions 2.1.3
		adorn: Adorn 2.2.0+1.17.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		advancementplaques: Advancement Plaques 1.4.1
		advancements-enlarger: Advancements Enlarger 0.2.4
		advdebug: Advancements Debug 2.3.0
		alaskanativecraft: Alaska Native Craft 1.3.1
		ambientenvironment: Ambient Environment 6.0.22
		amecsapi: Amecs API 1.1.4+mc21w16a
		appleskin: AppleSkin mc1.17-2.1.3
		appliedenergistics2: Applied Energistics 2 9.0.0-alpha.7
		aqupdcaracal: Caracal mob 1.17-1.3.2
		aqupdgrizzly: Grizzly Bear mob 1.17-1.2.0
		arcanus: Arcanus 1.20
		architectury: Architectury 2.6.35
		artifacts: Artifacts 5.0.2+fabric
		artifice: Artifice 0.15.3+21w07a
		attributefix: Attribute Fix {FABRIC} 1.0.3
		authme: Auth Me 1.5.0
		autoconfig1u: Auto Config v1 Updated 3.3.1
		axolotlitemfix: Axolotl Item Fix 1.1.2
		balm-fabric: Balm 1.3.0+0
		bannerpp: Banner++ 2.0.3+mc.1.17-rc1
		basicaiots: Basic AIOTs 1.3.1
		bclib: BCLib 0.3.1
		beenfo: Beenfo 1.17.1-fabric0.36.1-1.3.2
		betterdungeons: YUNG's Better Dungeons 1.17-1.0.2
		betterend: Better End 0.11.0-pre
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.1
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1.2
		biome_locator: Biome Locator 1.3.1
		bitsandchisels: BitsAndChisels 2.5.3
		blast: BLAST 1.8
		blockus: Blockus 2.2.10+1.17.1
		blue_endless_jankson: jankson 1.2.1
		bountiful: Bountiful 1.0.0
		breakprogress: Break Progress 1.0.1
		builtinservers: Builtin Servers 1.0.1-BETA+1.17
		campanion: Campanion 2.0.0-beta.1
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.1.0
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-world: Cardinal Components API (worlds) 3.0.0
		carrier: Carrier 1.8.0
		chalk: Chalk 1.0.1
		charm: Charm 3.3.2
		charmonium: Charmonium 3.3.0
		cherishedworlds: Cherished Worlds 2.0.1-1.17.1
		cloth-api: Cloth API 2.0.54
		cloth-armor-api-v1: Cloth Armor API v1 1.5.47
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v5 5.0.38
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		clumps: Clumps 7.0.10
		coat: Coat 1.0.0-beta.9
		colorfulsubtitles: Colorful Subtitles 1.0.0
		columns: Columns 1.2.0
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_github_shevek_parallelgzip: parallelgzip af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		conjuring: Conjuring 1.0.12
		controlling: Controlling For Fabric 1.1.2
		cosmetic-armor: Cosmetic Armor 1.1.0
		craftingtweaks: Crafting Tweaks 13.0.0+0
		croptopia: Croptopia 1.6.3
		crowdin-translate: CrowdinTranslate 1.3+1.17
		crusade: Crusade 1.2.4
		dankstorage: Dank Storage 2.2.1-1.17.1
		dark-enchanting: Dark Enchanting 0.4.1-1.17.1
		dark-loading-screen: Dark Loading Screen 1.6.11
		darkpaintings: Dark Paintings 4.0.2
		dawn: Dawn API 2.0.6
		deathlog: DeathLog 0.2.1
		defaultsettings: DefaultSettings 3.1.0
		diggusmaximus: Diggus Maximus 1.5.1-1.17
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		dml-refabricated: Deep Mob Learning: Refabricated 0.4.4-beta
		dml-refabricated-base: DML: Refabricated - Base 0.4.4-beta
		dml-refabricated-events: DML: Refabricated - Vanilla Events 0.4.4-beta
		dml-refabricated-modular-armor: DML: Refabricated - Glitch Armor 0.4.4-beta
		dml-refabricated-rei: DML: Refabricated - REI Integration 0.4.4-beta
		dmlsimulacrum: Deep Mob Learning: Simulacrum 1.0.5
		dual_riders: DualRiders 1.0.5
		dynamicfps: Dynamic FPS 2.0.6
		ecotones: Ecotones 0.8.1
		eggtab: Egg Tab 2.1.0+1.16-fabric
		enchantmentdescriptions: Enchantment Descriptions 4.0.1
		entitybanners: Entity Banners 1.0.2-BETA+1.17
		exdel: Explorer's Delight 1.0.0-beta.1
		expandability: ExpandAbility 4.0.2
		expandedstorage: Expanded Storage 7.2.7
		extended_armor_bars: Extended Armor Bars 1.1.0
		extragenerators: Extra Generators 1.1-BETA+1.17
		fabric: Fabric API 0.41.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931818
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+cbda931818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931818
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931818
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.3.0+57bef5a318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.10+fc40aa9d18
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931818
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+cbda931818
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.5+kotlin.1.5.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+cbda931818
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab6121d5
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.11+7931163218
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+cbda931818
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+cbda931818
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.4+7931163218
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4658223018
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.5+7931163218
		fabric-rendering-v1: Fabric Rendering (v1) 1.9.0+7931163218
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931818
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab61213d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.4.0+7931163218
		fabricloader: Fabric Loader 0.11.7
		fake-player-api: Fake Player API 0.2.0
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fasttransferlib: Fast Transfer Lib 0.5.6
		ferritecore: FerriteCore 3.1.0
		fiber: fiber 0.23.0-2
		fireworkfrenzy: Firework Frenzy 1.6
		flonters: Flonters 1.2.1+1.17.1
		flytre-lib-base: Flytre Lib - Base Module 1.2.0
		flytre-lib-compat: Flytre Lib - Compat Module 1.0.0
		flytre-lib-config: Flytre Lib - Config Module 1.1.0
		flytre-lib-event: Flytre Lib - Event Module 1.0.1
		flytre-lib-gui: Flytre Lib - GUI Module 1.0.0
		flytre-lib-storage: Flytre Lib - Storage Module 2.3.1
		flytre_lib: Flytre Lib 1.3.9
		gateofbabylon: Gate Of Babylon 1.5.1-1.17.1
		gbfabrictools: GBfabrictools 1.3.4+1.17
		geckolib3: Geckolib 3.0.19
		glassential: Glassential 1.17-1.2.0
		go-fish: Go Fish 1.3.0-beta-1.17.1
		golemsgalore: Golems Galore 1.0.3-1.17.1
		goml: Get Off My Lawn 1.4.0-beta
		graveyard: The Graveyard 1.0
		guild: Guild 0.3.3
		harvest_scythes: Harvest Scythes 2.0.6
		hctm-base: HCTM Base 3.6.2
		healthoverlay: Health Overlay 4.0.2
		hologram-api: Hologram API 0.2.1+1.17.1
		horseinfo: Horse Info 0.3.0-1.17
		horsestatsvanilla: Horse Stats Vanilla 4.1.8
		iknowwhatimdoing: I Know What I'm Doing 3.1.0
		impaled: Impaled 1.0.1
		improved-stations: Improved Stations 2.0.7
		incantationem: Incantationem 1.1.2+1.17.1
		indium: Indium 1.0.0+mc1.17.1
		indrev: Industrial Revolution 1.11.0-alpha.4
		inmis: Inmis 2.3.2-1.17.1
		inventorysorter: Inventory Sorter 1.8.0-1.17
		iris: Iris 1.1.2+build.9
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		jumpoverfences: JumpOverFences 1.16-0.0.3
		kambrik: Kambrik 1.1.0
		kibe: Kibe 1.9.3-BETA+1.17
		kjsextras: KubeJS Extras 1.4.0
		ktdatataglib: KtDataTagLib 1.5.4
		kubejs: KubeJS 1701.3.10-build.9999
		kyrptconfig: Kyrpt Config 1.2.1-1.17
		lakeside: Lakeside 1.1.0+1.17
		lazydfu: LazyDFU 0.1.2
		libaddict: libaddict 0.3.0
		libblockattributes_core: LibBlockAttributes (Core) 0.9.0
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.9.0
		libblockattributes_items: LibBlockAttributes (Items) 0.9.0
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.2.1+1.17.1
		libninepatch: LibNinePatch 1.1.0
		libzoomer: LibZoomer 0.2.1+1.17
		lifts: Lifts 1.3-BETA+1.17
		lightestlamp: Lightest Lamps 0.9.3
		lightoverlay: Light Overlay 6.0.1
		lithium: Lithium 0.7.4
		lovely_snails: Lovely Snails 1.0.3+1.17
		magicfungi: Magic Fungi 0.5.0-BETA+1.17.1
		magna: Magna 1.5.5-1.17-pre4
		mavm: More Axolotl Variants Mod 1.0.5
		maybe-data: Maybe data 1.0.1-1.17
		megane: megane 5.5.0
		megane-applied-energistics-2: megane-applied-energistics-2 5.5.0+9.0.0-alpha.2
		megane-base: megane-base 5.5.0
		megane-dml-simulacrum: megane-dml-simulacrum 5.5.0+1.0.5
		megane-extra-generators: megane-extra-generators 5.5.0+1.1-BETA-1.17
		megane-fabric-transfer: megane-fabric-transfer 5.5.0+1.3.0-fc40aa9d18
		megane-fast-transfer-lib: megane-fast-transfer-lib 5.5.0+0.5.7
		megane-industrial-revolution: megane-industrial-revolution 5.5.0+1.11.0-alpha.1
		megane-kibe: megane-kibe 5.5.0+1.9.1-BETA-1.17
		megane-lib-block-attributes: megane-lib-block-attributes 5.5.0+0.9.0
		megane-modern-industrialization: megane-modern-industrialization 5.5.0+0.5.12
		megane-reborn-core: megane-reborn-core 5.5.0+5.0.8-beta-build.111
		megane-runtime: megane-runtime 5.5.0
		megane-team-reborn-energy: megane-team-reborn-energy 5.5.0+2.0.0-beta1
		megane-tech-reborn: megane-tech-reborn 5.5.0+5.0.8-beta-build.111
		megane-vanilla: megane-vanilla 5.5.0+1.17.1
		megane-wireless-networks: megane-wireless-networks 5.5.0+1.3.0
		minecraft: Minecraft 1.17.1
		minershorizon: Miner's Horizon 1.7.0-1.17.1
		mm: Manningham Mills 2.3
		mo_glass: Mo Glass 1.5-MC1.17.1
		mocolors: Mo' Colors 1.2.2
		modern_industrialization: Modern Industrialization 0.6.0-alpha.02
		modmenu: Mod Menu 2.0.2
		morevillagers-fabric: MoreVillagersFabric 2.1.1-SNAPSHOT
		mostructures: Mo' Structures 1.3.0-pre1-1.17.1
		mousewheelie: Mouse Wheelie 1.7.3-newconfig+mc1.17.1-pre1
		mtmechs: Magitek Mechs 1.0.4
		myron: Myron 1.6.1
		mythic-mounts: Mythic Mounts 1.17.1-2.0
		naturescompass: Nature's Compass 1.17.1-2.0.1-fabric
		ninjaphenix_container_lib: NinjaPhenix's Container Library 1.2.4
		no-potion-offset: No Potion Offset ${version}
		noanglebrackets: NoAngleBrackets 1.1.0
		nyfsquivers: Nyf's Quivers Fabric-0.2.6
		okzoomer: Ok Zoomer 5.0.0-beta.2+1.17
		omega-config: OmegaConfig 1.0.8
		org_apache_commons_commons-compress: commons-compress 1.19
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_codehaus_groovy_groovy: groovy 3.0.8
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.8
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.0
		org_tukaani_xz: xz 1.8
		outvoted: Outvoted 1.5.0-b1
		owo: oωo 0.3.0
		packages: Packages 1.2.1
		packet_tweaker: Packet Tweaker 0.2.0+1.17.1
		patchouli: Patchouli 1.17.1-56-FABRIC
		placeholder-api: Placeholder API 1.1.1+1.17.1
		playerabilitylib: Pal 1.3.0
		pling: Pling 1.4.0
		polymer: Polymer 0.1.8+1.17.1
		promenade: Promenade 2.1.2
		qcommon-cfg-core: qcommon-cfg-core 3.3.0
		qcommon-croco: Croco 2.1.1
		quarrymod: Industial Quarry Mod 0.5.0
		quickshulker: Quick Shulker 1.3.0-1.17
		ratsmischief: Rat's Mischief 1.2.3
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.0.9-beta+build.131
		redbits: Red Bits 1.10.1
		repurposed_structures: Repurposed Structures 2.4.3+1.17.1
		respawnablepets: Respawnable Pets 1.17-5
		rhino: Rhino 1701.1.5-build.71
		riverredux: River Redux 0.2.0
		roughlyenoughitems: Roughly Enough Items 6.0.307-alpha
		rswires: RSWires 4.11.2
		rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
		runelic: Runelic 3.0.1
		secretrooms: Secret Rooms 1.1.0+1.17
		server_translations_api: Server Translations API 1.4.6+1.17
		sgui: SGui 1.0.0-rc4+1.17.1
		shulkerutils: shulkerutils 1.0.4-1.17
		skinlayers: 3d Skin Layers 1.1.1
		slight-gui-modifications: 'Slight' GUI Modifications 2.0.1
		slotlock: SlotLock 1.0.4-BETA+1.17
		smootherbedrock: Smoother Bedrock 1.0.2
		sodium: Sodium 0.3.2+IRIS2-build.9
		someforgepatchesported: Some Forge Patches Ported 1.0.1
		spruceui: SpruceUI 3.2.0+1.17
		stacc: Stacc 1.2.3
		staffofbuilding: Staff of Building 1.3.2-1.17
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.3
		strawdummy: Straw Dummy 1.5.0
		structurized: Structurized 1.3.0
		survivalisland: Survival Island 0.1.5
		team_reborn_energy: Energy 2.0.0-beta1
		techreborn: Tech Reborn 5.0.9-beta+build.131
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 2.0.0
		terraform-config-api-v1: Terraform Config API (v1) 2.0.0
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 2.0.0
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 2.0.0
		terraform-tree-api-v1: Terraform Tree API (v1) 2.0.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		terrarianslimes: Terrarian Slimes 1.1-BETA+1.17
		textile_backup: Textile Backup 2.2.0-1.17
		toolstats: Tool Stats 2.0.1
		tooltipfix: ToolTip Fix 1.0.4-1.17.1
		totemmod: Wither Totems Mod 0.3.2
		transportables: Transportables 1.0.6
		traverse: Traverse 4.0.0
		trident_return: TridentReturn 1.2.4
		trinkets: Trinkets 3.0.4
		truerooms: True Secret Rooms 1.1.5
		tweed4_annotated: tweed4_annotated 1.0.0
		tweed4_base: tweed4_base 1.0.0
		tweed4_data: tweed4_data 1.0.0
		tweed4_data_hjson: tweed4_data_hjson 1.0.0
		tweed4_tailor_coat: tweed4_tailor_coat 1.0.0
		tweed4_tailor_screen: tweed4_tailor_screen 1.0.0
		universal-graves: Universal Graves 1.1.3+1.17.1
		untitledduckmod: Untitled Duck Mod 0.3.0
		urns: Urns 1.0.1
		vanilla-hammers: Vanilla Hammers 3.1.2-1.17
		vanilla_degus: Vanilla Degus 1.2.3
		vanillaexcavators: Vanilla Excavators 1.1.0
		vanillaplusbiomes: Vanilla Plus Biomes 0.3.2
		villager-hats: Villager Hats Mod 1.2.1
		waystones: Waystones 2.1.2
		winged: Winged Mod 1.17.1-3.0.0
		wirelessnetworks: Wireless Networks 1.3.0
		wolveswitharmor: Wolves With Armor 1.6.1-1.17.1
		woods_and_mires: Woods and Mires 1.1.1+1.17
		wthit: wthit 3.10.0
		xaerominimap: Xaero's Minimap 21.20.0
		xaeroworldmap: Xaero's World Map 1.18.0
		yosbr: YOSBR 0.1.1
		yungsapi: YUNG's API 1.17-Fabric-19
		zihlaunchpads: ZIHLaunchpads 1.1.1
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Mesa Intel(R) UHD Graphics 630 (CFL GT2) GL version 4.6 (Core Profile) Mesa 21.2.2, Intel
	Window size: 1280x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, secretrooms:client_pack, Fabric Mods, charmonium/journeyman, kubejs:resource_pack (incompatible), file/Bare+Bones+1.17.zip
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i3-9100 CPU @ 3.60GHz
	Player Count: 1 / 8; [class_3222['tariqk'/85, l='ServerLevel[2021-10-23-SSP-HARD]', x=-482.83, y=70.00, z=-650.28]]
	Data Packs: vanilla, secretrooms:server_pack, Fabric Mods
#@!@# Game crashed! Crash report saved to: #@!@# /home/tariqk/.local/share/multimc/instances/All of Fabric 4 1.0.1/minecraft/crash-reports/crash-2021-10-30_16.43.07-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 255.
```
