### ISSUE TITLE
MP Server - Fabric 0.12.12 / 1.18.1 - Internal Server Error

### ISSUE THREAD

**Issue by kalinzange** [Tfarcenim/DankStorageFabric#51]
```
[01:00:39] [Server thread/WARN]: Failed to handle packet for /127.0.0.1:64059
net.minecraft.class_148: Ticking player
        at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.5) ~[?:?]
        at net.minecraft.server.network.ServerPlayerEntity.playerTick(ServerPlayerEntity:543) ~[?:?]
        at net.minecraft.server.network.ServerPlayNetworkHandler.tick(ServerPlayNetworkHandler:213) ~[?:?]
        at net.minecraft.network.ClientConnection.tick(ClientConnection:238) ~[?:?]
        at net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo:183) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:890) ~[server-intermediary.jar:?]
        at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:324) ~[?:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer:823) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:684) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "tfar.dankstorage.world.DankInventory.method_5439()" because "inv" is null
        at tfar.dankstorage.event.MixinHooks.onItemPickup(MixinHooks.java:47) ~[dankstorage-3.0.1-1.18.jar:?]
        at tfar.dankstorage.event.MixinHooks.interceptItem(MixinHooks.java:32) ~[dankstorage-3.0.1-1.18.jar:?]
        at net.minecraft.entity.player.PlayerInventory.handler$zoc000$interceptItems(PlayerInventory:1187) ~[?:?]
        at net.minecraft.entity.player.PlayerInventory.insertStack(PlayerInventory) ~[?:?]
        at net.minecraft.entity.ItemEntity.onPlayerCollision(ItemEntity:344) ~[?:?]
        at net.minecraft.entity.player.PlayerEntity.collideWithEntity(PlayerEntity:620) ~[?:?]
        at net.minecraft.entity.player.PlayerEntity.tickMovement(PlayerEntity:593) ~[?:?]
        at net.minecraft.entity.LivingEntity.tick(LivingEntity:2349) ~[?:?]
        at net.minecraft.entity.player.PlayerEntity.tick(PlayerEntity:274) ~[?:?]
        at net.minecraft.server.network.ServerPlayerEntity.playerTick(ServerPlayerEntity:479) ~[?:?]
        ... 9 more
[01:00:39] [Server thread/INFO]: kalinzange lost connection: Internal server error
[01:00:39] [Server thread/INFO]: kalinzange left the game
```

I can't make the server crash to get the crash report, so I had to edit my playerdata NBT file and set my self to spawn a bit far away from the item that was dropped (Bone)

**Comment by Tfarcenim** [comment]
Not sure what's causing this one, but I added some logging so now it will warn instead of crash the server.

**Comment by kalinzange** [comment]
I don't know what happened but also made my other danks emptied out. Yup, I went to my house opened my dank and it's empty

**Comment by kalinzange** [comment]
![image](https://user-images.githubusercontent.com/38161086/146557808-046f05fc-5a18-4190-bc89-33d647e3d182.png)
![image](https://user-images.githubusercontent.com/38161086/146557826-69b0e3cf-3021-41bb-a58b-89ece339a39a.png)

And the dank only tanks at 256 Blocks

**Comment by Tfarcenim** [comment]
Nothing I can do unfortunately without reproduction steps

**Comment by kalinzange** [comment]
It's understandable, I just found a bit weird how this happened.

I was at a Bastion and a skeleton came cross where I was going to murder her, when I actually killed the skeleton I got Internal Server Error, checked the console and there was that ticking player and some error related to Dank, I restarted the server, minecraft and had the same problem, joined the world and Internal Server Error

Decided to edit my player data and set myself a bit far away from the kill and I could join the server, picked up the bone and look at my dank was indeed empty. Decided to ignore since that dank was just netherrack, gravel, etc and flied around to mine some ancient debris, day after when I went home opened my danks to deposit what I had and there were empty and the Dank 6 didn't exceed the 256 Stacks like the dank I just had and used in the nether

The logs are from where I crashed, nothing really says than Ticking Player

[2021-12-17-2.log.gz](https://github.com/Tfarcenim/DankStorageFabric/files/7735728/2021-12-17-2.log.gz)
[2021-12-17-1.log.gz](https://github.com/Tfarcenim/DankStorageFabric/files/7735729/2021-12-17-1.log.gz)
[2021-12-17-3.log.gz](https://github.com/Tfarcenim/DankStorageFabric/files/7735730/2021-12-17-3.log.gz)

**Comment by Tfarcenim** [comment]
It looks like it triggered on item pickup, but I wasn't able to reproduce.

**Comment by kalinzange** [comment]
A friend of mine just joined the world and some other errors started to appear. Not sure if this helps tracing it
[DankLog.txt](https://github.com/Tfarcenim/DankStorageFabric/files/7736926/DankLog.txt)

Obviously his dank, was also empty

**Comment by kalinzange** [comment]
Do you have any discord link you can provide so we can chat more easily than through github issues?

**Comment by Tfarcenim** [comment]
https://discord.gg/vZxnfa4

**Comment by Tfarcenim** [comment]
This crash is no longer possible at all

**Comment by kalinzange** [comment]
```
[17:03:08] [Server thread/INFO]: [STDOUT]: Attempted to access a selected item from a null inventory
[17:03:08] [Server thread/INFO]: [STDOUT]: Attempted to access a selected item from a null inventory
[17:03:09] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2506ms or 50 ticks behind
[17:03:09] [Server thread/INFO]: [STDOUT]: Attempted to access a selected item from a null inventory
[17:03:18] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3913.method_17389()" because "$$0" is null
        at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.5) ~[?:?]
        at net.minecraft.screen.ScreenHandler.addProperties(ScreenHandler:121) ~[?:?]
        at tfar.dankstorage.container.AbstractDankMenu.<init>(AbstractDankMenu.java:26) ~[dankstorage-3.1-1.18.1.jar:?]
        at tfar.dankstorage.container.DockMenu.<init>(DockMenu.java:18) ~[dankstorage-3.1-1.18.1.jar:?]
        at tfar.dankstorage.container.DockMenu.t1s(DockMenu.java:54) ~[dankstorage-3.1-1.18.1.jar:?]
        at tfar.dankstorage.blockentity.DockBlockEntity.createMenu(DockBlockEntity.java:168) ~[dankstorage-3.1-1.18.1.jar:?]
        at tfar.dankstorage.blockentity.DockBlockEntity.createMenu(DockBlockEntity.java:32) ~[dankstorage-3.1-1.18.1.jar:?]
        at net.minecraft.server.network.ServerPlayerEntity.openHandledScreen(ServerPlayerEntity:1032) ~[?:?]
        at tfar.dankstorage.block.DockBlock.onUse(DockBlock.java:96) ~[dankstorage-3.1-1.18.1.jar:?]
        at net.minecraft.block.AbstractBlock$AbstractBlockState.onUse(AbstractBlock:937) ~[?:?]
        at net.minecraft.server.network.ServerPlayerInteractionManager.interactBlock(ServerPlayerInteractionManager:327) ~[?:?]
        at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractBlock(ServerPlayNetworkHandler:1057) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:30) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:8) ~[?:?]
        at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21) ~[?:?]
        at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
        at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:151) ~[?:?]
        at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:780) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:162) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125) ~[?:?]
        at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:762) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:756) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:110) ~[?:?]
        at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:740) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:688) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

It Still Happens even after updating the Dank Storage to the latest Version, I've left a message on the Dank Storage Channel but I didn't got any feedback from you
