### ISSUE TITLE
Pickblock doesn't work

### ISSUE THREAD

**Issue by WhitePhant0m** [Tfarcenim/DankStorageFabric#68]
mc ver: 1.18.1
dankstorage ver: 3.5
other mods: REI and it's dependencies

Also found this error in the log:
`[10:19:15] [Server thread/FATAL]: Error executing task on Server
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 9
	at java.util.Arrays$ArrayList.set(Unknown Source) ~[?:?]
	at net.minecraft.class_2371.set(class_2371.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.class_1277.method_5447(class_1277.java:136) ~[client-intermediary.jar:?]
	at tfar.dankstorage.item.DankItem.method_7884(DankItem.java:344) ~[dankstorage-1.18.1-3.5.jar:?]
	at net.minecraft.class_1799.method_7981(class_1799.java:240) ~[client-intermediary.jar:?]
	at net.minecraft.class_3225.method_14262(class_3225.java:347) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12046(class_3244.java:1057) ~[client-intermediary.jar:?]
	at net.minecraft.class_2885.method_12547(class_2885.java:30) ~[client-intermediary.jar:?]
	at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:780) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:162) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:762) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:756) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:740) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:688) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]`

Not sure if it's related.

**Comment by Tfarcenim** [comment]
That error is an unrelated bug.

I forgot to reenable pick block functionality after redoing most of the mod.
